// <auto-generated />
using System;
using LearningPlatformSystem.Infrastructure.Persistence.EFC;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningPlatformSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LearningPlatformDbContext))]
    [Migration("20260220101332_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CampusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Campuses", (string)null);
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.ClassroomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Classrooms", (string)null);
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CourseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SubcategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SubcategoryId");

                    b.HasIndex("SubcategoryId", "Title")
                        .IsUnique();

                    b.ToTable("Courses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Courses_Credits_Range", "[Credits] BETWEEN 1 AND 30");
                        });
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CoursePeriodEnrollmentEntity", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoursePeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("StudentId", "CoursePeriodId");

                    b.HasIndex("CoursePeriodId");

                    b.ToTable("CoursePeriodEnrollments", (string)null);
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CoursePeriodEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CampusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CampusId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StartDate");

                    b.HasIndex("TeacherId");

                    b.ToTable("CoursePeriods", (string)null);
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CoursePeriodResourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoursePeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CoursePeriodId");

                    b.ToTable("CoursePeriodResources", (string)null);
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CoursePeriodReviewEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("CoursePeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("CoursePeriodId", "StudentId")
                        .IsUnique();

                    b.ToTable("CoursePeriodReviews", (string)null);
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CourseSessionAttendanceEntity", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StudentId", "CourseSessionId");

                    b.HasIndex("CourseSessionId");

                    b.ToTable("CourseSessionAttendances", (string)null);
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CourseSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassroomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoursePeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("CoursePeriodId");

                    b.ToTable("CourseSessions", (string)null);
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.StudentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.SubcategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CategoryEntityId");

                    b.HasIndex("CategoryId", "Name")
                        .IsUnique();

                    b.ToTable("Subcategories", (string)null);
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.TeacherEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CampusEntity", b =>
                {
                    b.OwnsOne("LearningPlatformSystem.Domain.Shared.ValueObjects.Addresses.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CampusEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("City");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("nvarchar(6)")
                                .HasColumnName("PostalCode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Street");

                            b1.HasKey("CampusEntityId");

                            b1.ToTable("Campuses");

                            b1.WithOwner()
                                .HasForeignKey("CampusEntityId");
                        });

                    b.OwnsOne("LearningPlatformSystem.Domain.Shared.ValueObjects.ContactInformations.ContactInformation", "ContactInformation", b1 =>
                        {
                            b1.Property<Guid>("CampusEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Email");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("CampusEntityId");

                            b1.ToTable("Campuses");

                            b1.WithOwner()
                                .HasForeignKey("CampusEntityId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("ContactInformation");
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CourseEntity", b =>
                {
                    b.HasOne("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.SubcategoryEntity", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CoursePeriodEnrollmentEntity", b =>
                {
                    b.HasOne("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CoursePeriodEntity", "CoursePeriod")
                        .WithMany("Enrollments")
                        .HasForeignKey("CoursePeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.StudentEntity", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoursePeriod");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CoursePeriodEntity", b =>
                {
                    b.HasOne("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CampusEntity", "Campus")
                        .WithMany()
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CourseEntity", "Course")
                        .WithMany("CoursePeriods")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.TeacherEntity", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campus");

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CoursePeriodResourceEntity", b =>
                {
                    b.HasOne("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CoursePeriodEntity", "CoursePeriod")
                        .WithMany("Resources")
                        .HasForeignKey("CoursePeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoursePeriod");
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CoursePeriodReviewEntity", b =>
                {
                    b.HasOne("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CoursePeriodEntity", "CoursePeriod")
                        .WithMany("Reviews")
                        .HasForeignKey("CoursePeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.StudentEntity", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoursePeriod");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CourseSessionAttendanceEntity", b =>
                {
                    b.HasOne("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CourseSessionEntity", "CourseSession")
                        .WithMany("Attendances")
                        .HasForeignKey("CourseSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.StudentEntity", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseSession");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CourseSessionEntity", b =>
                {
                    b.HasOne("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.ClassroomEntity", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CoursePeriodEntity", "CoursePeriod")
                        .WithMany("Sessions")
                        .HasForeignKey("CoursePeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("CoursePeriod");
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.StudentEntity", b =>
                {
                    b.OwnsOne("LearningPlatformSystem.Domain.Shared.ValueObjects.Addresses.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("StudentEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("City");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("nvarchar(6)")
                                .HasColumnName("PostalCode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Street");

                            b1.HasKey("StudentEntityId");

                            b1.ToTable("Students");

                            b1.WithOwner()
                                .HasForeignKey("StudentEntityId");
                        });

                    b.OwnsOne("LearningPlatformSystem.Domain.Shared.ValueObjects.ContactInformations.ContactInformation", "ContactInformation", b1 =>
                        {
                            b1.Property<Guid>("StudentEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Email");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("StudentEntityId");

                            b1.HasIndex("Email")
                                .IsUnique();

                            b1.ToTable("Students");

                            b1.WithOwner()
                                .HasForeignKey("StudentEntityId");
                        });

                    b.OwnsOne("LearningPlatformSystem.Domain.Shared.ValueObjects.PersonNames.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("StudentEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("LastName");

                            b1.HasKey("StudentEntityId");

                            b1.HasIndex("FirstName", "LastName");

                            b1.ToTable("Students");

                            b1.WithOwner()
                                .HasForeignKey("StudentEntityId");
                        });

                    b.Navigation("Address");

                    b.Navigation("ContactInformation")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.SubcategoryEntity", b =>
                {
                    b.HasOne("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CategoryEntity", null)
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryEntityId");

                    b.HasOne("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.TeacherEntity", b =>
                {
                    b.OwnsOne("LearningPlatformSystem.Domain.Shared.ValueObjects.Addresses.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("TeacherEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("City");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("nvarchar(6)")
                                .HasColumnName("PostalCode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Street");

                            b1.HasKey("TeacherEntityId");

                            b1.ToTable("Teachers");

                            b1.WithOwner()
                                .HasForeignKey("TeacherEntityId");
                        });

                    b.OwnsOne("LearningPlatformSystem.Domain.Shared.ValueObjects.ContactInformations.ContactInformation", "ContactInformation", b1 =>
                        {
                            b1.Property<Guid>("TeacherEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Email");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("TeacherEntityId");

                            b1.HasIndex("Email")
                                .IsUnique();

                            b1.ToTable("Teachers");

                            b1.WithOwner()
                                .HasForeignKey("TeacherEntityId");
                        });

                    b.OwnsOne("LearningPlatformSystem.Domain.Shared.ValueObjects.PersonNames.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("TeacherEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("LastName");

                            b1.HasKey("TeacherEntityId");

                            b1.ToTable("Teachers");

                            b1.WithOwner()
                                .HasForeignKey("TeacherEntityId");
                        });

                    b.Navigation("Address");

                    b.Navigation("ContactInformation")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CategoryEntity", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CourseEntity", b =>
                {
                    b.Navigation("CoursePeriods");
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CoursePeriodEntity", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Resources");

                    b.Navigation("Reviews");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("LearningPlatformSystem.Infrastructure.Persistence.EFC.Entities.CourseSessionEntity", b =>
                {
                    b.Navigation("Attendances");
                });
#pragma warning restore 612, 618
        }
    }
}
